definitions:
  response.Response:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /base/captcha:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":200,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 生成验证码
      tags:
      - base
  /base/captcha/:captchaId:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":200,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 生成验证码图片路径
      tags:
      - base
  /base/captcha/verify:
    post:
      consumes:
      - application/json
      parameters:
      - description: "1"
        in: query
        name: captchaId
        required: true
        type: string
      - description: "1"
        in: query
        name: Captcha
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"Code":200,"data":{},"msg":"获取成功"}'
          schema:
            type: string
      summary: 校验验证吗
      tags:
      - base
  /book/detail/{bookId}:
    get:
      consumes:
      - application/json
      description: 书详情
      parameters:
      - description: "1"
        in: path
        name: bookId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            x-token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 书详情
      tags:
      - book
  /book/list:
    get:
      consumes:
      - application/json
      description: 获取书籍列表
      parameters:
      - description: "1"
        in: query
        name: pageNum
        required: true
        type: integer
      - description: "10"
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            x-token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 获取书籍列表
      tags:
      - book
  /book/query:
    get:
      consumes:
      - application/json
      description: 搜索书
      parameters:
      - description: 三体
        in: query
        name: query
        required: true
        type: string
      - description: "1"
        in: query
        name: pageNum
        required: true
        type: integer
      - description: "10"
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            x-token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 搜索书
      tags:
      - book
  /section/list:
    get:
      consumes:
      - application/json
      description: 章节列表
      parameters:
      - description: "1"
        in: query
        name: pageNum
        required: true
        type: integer
      - description: "10"
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            x-token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 章节列表
      tags:
      - section
  /section/list/{bookId}:
    get:
      consumes:
      - application/json
      description: 查询书下所有章节信息
      parameters:
      - description: "1"
        in: path
        name: bookId
        required: true
        type: integer
      - description: "1"
        in: query
        name: pageNum
        required: true
        type: integer
      - description: "50"
        in: query
        name: pageSize
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            x-token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询书下所有章节信息
      tags:
      - section
  /section/one/{sectionId}:
    get:
      consumes:
      - application/json
      description: 查询当前章节内容
      parameters:
      - description: "1"
        in: path
        name: sectionId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            x-token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: 查询当前章节内容
      tags:
      - section
  /syn:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            x-token:
              description: qwerty
              type: string
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Response'
      summary: mysql数据同步到ES
      tags:
      - base
swagger: "2.0"
